git add macros.h
git add main.c
git add README.md
git add run-avrdude
git add Makefile
git add USART.c
git add gitadd.sh
git add pinDefines.h
git add sfr_helper.h
git add USART.h
git add binaryMacro.h
git add portpins.h
git add test_float.cx
git add DS1620.txt
git add README.md
git add DS1620.c
git add DS16202.c
git add DS16203.c
git add DS16204.c
git add DS1620.h
git add test_DS1620.cx
git status
